# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: gtcr-indexer
contracts:
  - name: LightGTCRFactory
    handler: src/mappings/index.ts
    events:
      - event: NewGTCR(address indexed _address)
  - name: LightGeneralizedTCR
    handler: src/mappings/index.ts
    events:
      - event: ConnectedTCRSet(address indexed _connectedTCR)
      - event: Contribution(bytes32 indexed _itemID, uint256 _requestID, uint256 _roundID, address indexed _contributor, uint256 _contribution, uint8 _side)
      - event: Dispute(address indexed _arbitrator, uint256 indexed _disputeID, uint256 _metaEvidenceID, uint256 _evidenceGroupID)
        field_selection:
          transaction_fields:
            - from
      - event: Evidence(address indexed _arbitrator, uint256 indexed _evidenceGroupID, address indexed _party, string _evidence)
        field_selection:
          transaction_fields:
            - hash
      - event: ItemStatusChange(bytes32 indexed _itemID, bool _updatedDirectly)
        field_selection:
          transaction_fields:
            - hash
      - event: MetaEvidence(uint256 indexed _metaEvidenceID, string _evidence)
      - event: NewItem(bytes32 indexed _itemID, string _data, bool _addedDirectly)
      - event: RequestSubmitted(bytes32 indexed _itemID, uint256 _evidenceGroupID)
        field_selection:
          transaction_fields:
            - from
            - hash
      - event: RewardWithdrawn(address indexed _beneficiary, bytes32 indexed _itemID, uint256 _request, uint256 _round, uint256 _reward)
      - event: Ruling(address indexed _arbitrator, uint256 indexed _disputeID, uint256 _ruling)
  - name: LIArbitrator
    handler: src/mappings/index.ts
    events:
      - event: AppealPossible(uint256 indexed _disputeID, address indexed _arbitrable)
        field_selection:
          transaction_fields:
            - hash
      - event: AppealDecision(uint256 indexed _disputeID, address indexed _arbitrable)
        field_selection:
          transaction_fields:
            - hash
  - name: GTCRFactory
    handler: src/mappings/index.ts
    events:
      - event: NewGTCR(address indexed _address)
  - name: GeneralizedTCR
    handler: src/mappings/index.ts
    events:
      - event: AppealContribution(bytes32 indexed _itemID, address indexed _contributor, uint256 indexed _request, uint256 _round, uint256 _amount, uint8 _side)
      - event: ConnectedTCRSet(address indexed _connectedTCR)
      - event: Dispute(address indexed _arbitrator, uint256 indexed _disputeID, uint256 _metaEvidenceID, uint256 _evidenceGroupID)
      - event: Evidence(address indexed _arbitrator, uint256 indexed _evidenceGroupID, address indexed _party, string _evidence)
      - event: HasPaidAppealFee(bytes32 indexed _itemID, uint256 indexed _request, uint256 indexed _round, uint8 _side)
      - event: ItemStatusChange(bytes32 indexed _itemID, uint256 indexed _requestIndex, uint256 indexed _roundIndex, bool _disputed, bool _resolved)
      - event: ItemSubmitted(bytes32 indexed _itemID, address indexed _submitter, uint256 indexed _evidenceGroupID, bytes _data)
      - event: MetaEvidence(uint256 indexed _metaEvidenceID, string _evidence)
      - event: RequestEvidenceGroupID(bytes32 indexed _itemID, uint256 indexed _requestIndex, uint256 indexed _evidenceGroupID)
      - event: RequestSubmitted(bytes32 indexed _itemID, uint256 indexed _requestIndex, uint8 indexed _requestType)
      - event: Ruling(address indexed _arbitrator, uint256 indexed _disputeID, uint256 _ruling)
  - name: IArbitrator
    handler: src/mappings/index.ts
    events:
      - event: AppealPossible(uint256 indexed _disputeID, address indexed _arbitrable)
        field_selection:
          transaction_fields:
            - hash
      - event: AppealDecision(uint256 indexed _disputeID, address indexed _arbitrable)
        field_selection:
          transaction_fields:
            - hash
networks:
  - id: 100
    start_block: 16969180
    contracts:
      - name: LightGTCRFactory
        address:
          - 0x08e58Bc26CFB0d346bABD253A1799866F269805a
        start_block: 19592773
      - name: LightGeneralizedTCR
      - name: LIArbitrator
      - name: GTCRFactory
        address:
          - 0x794Cee5a6e1501b633eC13b8c1e327d9860FE039
        start_block: 16969180
      - name: GeneralizedTCR
      - name: IArbitrator

unordered_multichain_mode: true
